- name: 全局配置
  data:
   - name: Site Source
     desc: 改变 Jekyll 读取文件的目录
     config: "source: DIR"
     command: -s, --source DIR

   - name: Site Destination
     desc: 改变 Jekyll 写入文件的目录
     config: "destination: DIR"
     command: -d, --destination DIR

   - name: Safe
     desc: 禁用自定义插件
     config: "safe: BOOL"
     command: --safe

   - name: Keep files
     desc: 当清除site写入文件的目录时，保存选中的文件。对于非Jekyll生成的文件比较有用。路径是相对于写入文件的目录的。
     config: "keep_files: [DIR, FILE, ...]"

   - name: Exclude
     desc: 转换时排除某些文件夹或文件。被排除的文件或文件夹的路径是相对于网站源码目录的，源码目录以外不受影响。
     config: "exclude: [DIR, FILE, ...]"

   - name: Include
     desc: 转换时强制包含某些文件、文件夹。.htaccess是个典型的例子，因为默认排除 .(dot)开头的文件。
     config: "include: [DIR, FILE, ...]"

   - name: Time Zone
     desc: 设置时区，默认值为操作系统的时区
     config: "timezone: TIMEZONE"

   - name: Encoding
     desc: 设置文件的编码
     config: "encoding: ENCODING"

- name: build命令参数/选项
  data:
   - name: Regeneration
     desc: 允许文件修改时自动重新生成网站
     command: -w, --watch

   - name: Configuration
     desc: 手动设置配置文件并替代_config.yml，可设置多个，且后边的设置会覆盖前边的
     command: --config FILE1[,FILE2,...]

   - name: Drafts
     desc: 处理草稿
     config: "show_drafts: BOOL"
     command: --drafts

   - name: Future
     desc: 用将来的日期发布文章
     config: "future: BOOL"
     command: --future

   - name: LSI
     desc: 为相关文章生成索引
     config: "lsi: BOOL"
     command: --lsi

   - name: Limit Posts
     desc: 限制文章的数量
     config: "limit_posts: NUM"
     command: --limit_posts NUM

   - name: Environment
     desc: 使用特定环境值进行编译
     command: JEKYLL_ENV=production

   - name: Force polling
     desc: 强制使用轮询watch
     command: --force_polling

   - name: Verbose output
     desc: 冗值输出
     command: -V, --verbose

   - name: Silence Output
     desc: 静默输出
     command: -q, --quiet

   - name: Incremental build
     desc: 开启实验性的渐进编译特性。渐进编译只重新编译那些有改变的页面和文章，这可以使大型站点的性能得到大大提升。但是也可能会破坏当前的站点实例
     config: "incremental: BOOL"
     command: -I, --incremental

   - name: Liquid profiler
     desc: Generate a Liquid rendering profile to help you identify performance bottlenecks
     config: "profile: BOOL"
     command: --profile

- name: server命令参数/选项
  desc: Jekyll运行server命令前是需要在后台先运行build命令的，所以build命令的参数或选项都可以用在server命令下。此外，server还支持以下参数/选项
  data:
   - name: Local Server Port
     desc: 监听所给的端口
     config: "port: PORT"
     command: --port PORT

   - name: Local Server Hostname
     desc: 监听所给的主机名
     config: "host: HOSTNAME"
     command: --host HOSTNAME

   - name: Base URL
     desc: 网站的根路径
     config: "baseurl: URL"
     command: --baseurl URL

   - name: Detach
     desc: 从终端命令行中分离出来
     config: "detach: BOOL"
     command: -B, --detach

   - name: Skips the initial site build
     desc: 跳过server命令之前的编译
     command: --skip-initial-build

   - name: X.509 (SSL) Private Key
     desc: SSL密钥
     command: --ssl-key

   - name: X.509 (SSL) Certificate
     desc: SSL公共证书
     command: --ssl-cert
